# Use this file to run client server and nginx together

version: '3'
services:
  # TOURS Client
  tours-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./tours-client:/app
    env_file:
      - ./tours-client/config.env

  # TOURS API
  tours-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./tours-server
    volumes:
      - node_modules:/app/node_modules
        # - /app/node_modules For some reason this does not work
      - ./tours-server:/app
    env_file:
      - ./tours-server/config.env

  # TOURS PROXY SERVER
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '1337:80'

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./local/path/to/node_modules
