# TOURS SERVER: Production

version: '3'
services:
  # TOURS API
  tours-server:
    build:
      dockerfile: Dockerfile.prod
      context: ./tours-server

  # TOURS PROXY SERVER
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - '1337:80'
