FROM node:alpine

WORKDIR "/app"

COPY ./package.json ./
RUN npm install
COPY ./ ./ 

# EXPOSE 3000
# Container is built using above image and steps

# Use this cmd to run the container
CMD ["npm","start"]