FROM node:alpine

WORKDIR "/app"

COPY ./package.json ./
RUN npm install
COPY ./ ./ 

EXPOSE 1337
# Container is built using above image and steps

# Use this cmd to run the container
CMD ["npm", "run", "dev"]