version: '3'
services:
  tours-ts-node-app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:1337'
    volumes:
      # - node_modules:/app/node_modules
      - /app/node_modules
      - ./:/app
    env_file:
      - ./config.env
# volumes:
#   node_modules:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./local/path/to/node_modules
