name: heroku-tours-server-depl

on:
  push:
    branches:
      - master
    paths:
      - 'tours-server/**'
      - 'nginx/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./tours-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: docker build -f Dockerfile.prod -t dvgy/tours-server-heroku .
      - run: docker images
      - name: Login to conatiner registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Push to Container
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}        
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 

      - name: Realase Container
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}         
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 
        

